How to convert XElement object into a dataset or datatable ?
I'm accessing a SharePoint ( 2007 ) list through a service reference of lists.asmx created in my console application . Console application is created in VS2012 and .Net 4.5 framework . @codeSnippetRemoved
I need to convert the XML returned in items XElement to dataset / datatable and pass it to a stored procedure written in SQL Server 2008 R2 .
I tried using following code but it gave me error @codeSnippetRemoved
khushi , check this may be useful to you .... @codeSnippetRemoved
some references : http://www.dotnetpickles.com/2014/02/aspnet-convert-xml-to-datatable-in-cnet.html
