Change HorizontalGridLinesBrush only for selected Row
In a WPF DataGrid the Color of the Horizontal Grid Line can be modified by the HorizontalGridLinesBrush Property .
Some Items have a boolean Property set to true so I want to highlight them with the Horizontal Grid Line Brush set to another Color .
Is it possible to change the Color of the Horizontal Grid Line only for cetain Rows ?
DataGrid.HorizontalGridLinesBrush is set per DataGrid so you cannot change it per row but you could replace default horizontal line behaviour by disabling horizontal grid lines and creating custom DataGridRow style
