ajax adding information to database
im still fairly new to the whole ruby on rails stuff , though i have read that you can easily perform ajax requests . what im trying to do is add a new row to the database table , and pass a few variables from it .
what i have at present is @codeSnippetRemoved
though how does it know what variables to pass to the database ?
this is what is happening at present
If you want to pass information to your rails app , you will need to place the @codeSnippetRemoved
on to the form_for tag , then your controller will be able to pass those params on to your model .
If you want to pass more than one variable to the server you include them in the http request . This is true for AJAX requests as well as regular ones . For example : @codeSnippetRemoved
Often though with more complex submissions you'll want to use a remote form rather than just a simple link .
